name: Build Miku UI GSI 

on:
workflow_dispatch: # Позволяет запускать сборку вручную кнопкой 

jobs:
build:
runs-on: ubuntu-22.04
steps:
- name: Checkout Repository
uses: actions/checkout@v4 

* name: Free Disk Space
run: |
sudo rm -rf /usr/share/dotnet
sudo rm -rf /usr/local/lib/android
sudo rm -rf /opt/ghc
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"
* name: Set up Environment
run: |
sudo apt update
sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev lib32ncurses-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfigbc
* name: Run Build Script
run: |
chmod +x build.sh
./build.sh
* name: Upload GSI Artifact
uses: actions/upload-artifact@v4
with:
name: MikuUI-GSI
path: ./*.img # Скрипт ищет готовый файл .img в корне папки
